In [1]:
print("你好！这是我的第一个 Jupyter Notebook 代码")

# 简单数学运算
result = 5 + 3
print(f"5 + 3 = {result}")

a = 10
b = 5
sum_ab = a + b
diff_ab = a - b
print(f"a = {a}, b = {b}")
print(f"a + b = {sum_ab}")
print(f"a - b = {diff_ab}")

你好！这是我的第一个 Jupyter Notebook 代码
5 + 3 = 8
a = 10, b = 5
a + b = 15
a - b = 5


In [2]:
import numpy as np

# 定义两个 2x2 矩阵
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("=== 矩阵 A ===")
print(matrix_a)
print("\n=== 矩阵 B ===")
print(matrix_b)

# 矩阵加法
print("\n=== 矩阵加法 A + B ===")
print(matrix_a + matrix_b)

# 矩阵乘法
print("\n=== 矩阵乘法 A × B ===")
print(np.dot(matrix_a, matrix_b))

# 矩阵转置
print("\n=== 矩阵 A 的转置 ===")
print(matrix_a.T)

=== 矩阵 A ===
[[1 2]
 [3 4]]

=== 矩阵 B ===
[[5 6]
 [7 8]]

=== 矩阵加法 A + B ===
[[ 6  8]
 [10 12]]

=== 矩阵乘法 A × B ===
[[19 22]
 [43 50]]

=== 矩阵 A 的转置 ===
[[1 3]
 [2 4]]
